'use server'

import { createClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import type { ProjectStatus, DesignStatus, TeamRole } from '@/lib/types'

// ---------- Helpers ----------

/** Look up the current user's team_member record from their auth session. */
async function getCurrentTeamMember(supabase: Awaited<ReturnType<typeof createClient>>) {
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return null

  const { data: member } = await supabase
    .from('team_members')
    .select('id, role')
    .eq('auth_user_id', user.id)
    .single()

  return member as { id: string; role: TeamRole } | null
}

/** Roles that can create projects */
const CREATE_ROLES: TeamRole[] = ['admin', 'strategist', 'jr_strategist']

/** Roles that can update any field on a project */
const FULL_UPDATE_ROLES: TeamRole[] = ['admin', 'strategist', 'jr_strategist', 'manager', 'senior_editor', 'senior_writer', 'senior_designer']

/** Per-role field allowlists for restricted roles */
const ROLE_FIELD_ALLOWLIST: Partial<Record<TeamRole, string[]>> = {
  writer: ['script_url', 'notes'],
  editor: ['edit_url', 'edit_version', 'thumbnail_url', 'notes'],
  designer: ['design_status', 'thumbnail_url'],
}

// ---------- Create ----------

export interface CreateProjectInput {
  title: string
  client_id: string
  writer_id?: string | null
  editor_id?: string | null
  notes?: string | null
}

export async function createProject(input: CreateProjectInput) {
  const supabase = await createClient()
  const member = await getCurrentTeamMember(supabase)
  if (!member) return { error: 'Unauthorized', project: null }

  if (!CREATE_ROLES.includes(member.role)) {
    return { error: 'Only Admins, Strategists, and Jr Strategists can create projects.', project: null }
  }

  if (!input.title?.trim()) {
    return { error: 'Project title is required.', project: null }
  }
  if (!input.client_id?.trim()) {
    return { error: 'Client is required.', project: null }
  }

  // Insert project — task_number is auto-generated by DB trigger
  const { data: project, error: insertError } = await supabase
    .from('projects')
    .insert({
      title: input.title.trim(),
      client_id: input.client_id,
      status: 'idea' as ProjectStatus,
      writer_id: input.writer_id || null,
      editor_id: input.editor_id || null,
      notes: input.notes || null,
    })
    .select()
    .single()

  if (insertError) return { error: insertError.message, project: null }

  // Log creation to project_status_history
  const { error: historyError } = await supabase
    .from('project_status_history')
    .insert({
      project_id: project.id,
      from_status: null,
      to_status: 'idea' as ProjectStatus,
      changed_by: member.id,
      notes: 'Project created',
    })

  if (historyError) {
    console.error('Failed to log project creation to history:', historyError.message)
    // Non-fatal — the project was already created
  }

  revalidatePath('/pipeline')
  revalidatePath(`/clients/${input.client_id}`)
  return { error: null, project }
}

// ---------- Read ----------

export async function getProject(id: string) {
  const supabase = await createClient()

  const { data, error } = await supabase
    .from('projects')
    .select(`
      *,
      clients!inner ( name, pod_id, pods ( name ) ),
      writer:team_members!projects_writer_id_fkey ( first_name, last_name ),
      editor:team_members!projects_editor_id_fkey ( first_name, last_name )
    `)
    .eq('id', id)
    .single()

  if (error) throw error

  // Flatten the joined data into ProjectWithRelations shape
  const client = data.clients as any
  const writer = data.writer as any
  const editor = data.editor as any

  return {
    ...data,
    clients: undefined,
    writer: undefined,
    editor: undefined,
    client_name: client?.name ?? '',
    pod_id: client?.pod_id ?? null,
    pod_name: client?.pods?.name ?? null,
    writer_name: writer ? `${writer.first_name} ${writer.last_name}` : null,
    editor_name: editor ? `${editor.first_name} ${editor.last_name}` : null,
  }
}

// ---------- Update ----------

export interface UpdateProjectInput {
  title?: string
  notes?: string | null
  script_v1_due?: string | null
  edit_due?: string | null
  publish_due?: string | null
  script_url?: string | null
  edit_url?: string | null
  thumbnail_url?: string | null
  edit_version?: number
  design_status?: DesignStatus
  writer_id?: string | null
  editor_id?: string | null
}

export async function updateProject(id: string, input: UpdateProjectInput) {
  const supabase = await createClient()
  const member = await getCurrentTeamMember(supabase)
  if (!member) return { error: 'Unauthorized' }

  // Determine which fields this role is allowed to update
  let allowedFields: Record<string, unknown>

  if (FULL_UPDATE_ROLES.includes(member.role)) {
    // Admins, strategists, jr_strategists, managers can update anything
    allowedFields = { ...input }
  } else {
    // Restricted roles — only allow their permitted fields
    const allowlist = ROLE_FIELD_ALLOWLIST[member.role]
    if (!allowlist) {
      return { error: 'Your role does not have permission to update projects.' }
    }

    allowedFields = {}
    for (const field of allowlist) {
      if (field in input) {
        allowedFields[field] = (input as Record<string, unknown>)[field]
      }
    }

    if (Object.keys(allowedFields).length === 0) {
      return { error: 'No permitted fields in update.' }
    }
  }

  // Validate title if being updated
  if ('title' in allowedFields && typeof allowedFields.title === 'string') {
    if (!allowedFields.title.trim()) {
      return { error: 'Project title cannot be empty.' }
    }
    allowedFields.title = (allowedFields.title as string).trim()
  }

  const { error } = await supabase
    .from('projects')
    .update(allowedFields)
    .eq('id', id)

  if (error) return { error: error.message }

  revalidatePath('/pipeline')
  revalidatePath(`/projects/${id}`)
  return { error: null }
}

// ---------- Delete ----------

export async function deleteProject(id: string) {
  const supabase = await createClient()
  const member = await getCurrentTeamMember(supabase)
  if (!member) return { error: 'Unauthorized' }

  if (member.role !== 'admin') {
    return { error: 'Only admins can delete projects.' }
  }

  const { error } = await supabase
    .from('projects')
    .delete()
    .eq('id', id)

  if (error) return { error: error.message }

  revalidatePath('/pipeline')
  return { error: null }
}
