-- 006_module2_prep.sql — Module 2 preparation: RLS fix + seed data for boards
-- Applied: 2026-04-02

-- ============================================================================
-- BUG-22: Allow all authenticated users to UPDATE projects
-- The existing "projects_all" FOR ALL policy only permits admin/strategist/
-- jr_strategist. Managers, editors, writers, and other roles need to update
-- project status (transitions are validated in server actions, not RLS).
-- ============================================================================
CREATE POLICY "projects_update" ON projects
  FOR UPDATE TO authenticated
  USING (true);

-- ============================================================================
-- BUG-25: Seed team members have no auth_user_id (except admin)
-- NOTE: Real auth users cannot be created in a SQL migration. Each test team
-- member needs a corresponding auth.users row created via Supabase Dashboard
-- (Auth → Users), then linked here with:
--   UPDATE team_members SET auth_user_id = '<UUID>' WHERE email = '<email>';
-- This must be done manually per environment.
-- ============================================================================

-- ============================================================================
-- BUG-26: Seed client_assignments for board testing
-- Without these, role-based board queries return empty results.
-- ============================================================================

-- Acme Co assignments
INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'strategist'
FROM clients c, team_members tm
WHERE c.name = 'Acme Co' AND tm.first_name = 'Clayton' AND tm.last_name = 'Test';

INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'manager'
FROM clients c, team_members tm
WHERE c.name = 'Acme Co' AND tm.first_name = 'Paulo' AND tm.last_name = 'Test';

INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'senior_editor'
FROM clients c, team_members tm
WHERE c.name = 'Acme Co' AND tm.first_name = 'Raj' AND tm.last_name = 'Test';

INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'designer'
FROM clients c, team_members tm
WHERE c.name = 'Acme Co' AND tm.first_name = 'Tess' AND tm.last_name = 'Test';

-- BrightPath Media assignments
INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'strategist'
FROM clients c, team_members tm
WHERE c.name = 'BrightPath Media' AND tm.first_name = 'Clayton' AND tm.last_name = 'Test';

INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
SELECT c.id, tm.id, 'manager'
FROM clients c, team_members tm
WHERE c.name = 'BrightPath Media' AND tm.first_name = 'Paulo' AND tm.last_name = 'Test';

-- ============================================================================
-- BUG-27: Seed supervised_by for Senior Writer/Editor boards
-- Without supervision relationships, Senior Writer and Senior Editor board
-- queries (which filter by supervised_by = current_user) return no results.
-- ============================================================================

-- Marcus (Writer) and Sofia (Writer) supervised by Maria (Senior Writer)
UPDATE team_members SET supervised_by = (SELECT id FROM team_members WHERE first_name = 'Maria' AND last_name = 'Test')
WHERE first_name IN ('Marcus', 'Sofia') AND last_name = 'Test';

-- Leo (Editor) supervised by Raj (Senior Editor)
UPDATE team_members SET supervised_by = (SELECT id FROM team_members WHERE first_name = 'Raj' AND last_name = 'Test')
WHERE first_name = 'Leo' AND last_name = 'Test';

-- ============================================================================
-- BUG-28: Seed projects for pipeline/Kanban development
-- Creates sample projects across multiple statuses so board columns aren't
-- empty during Module 2 development. task_number is auto-generated by trigger.
-- ============================================================================

INSERT INTO projects (title, client_id, status, writer_id, editor_id)
SELECT 'How to Scale a YouTube Channel in 2026', c.id, 'scriptwriting',
  (SELECT id FROM team_members WHERE first_name = 'Marcus' AND last_name = 'Test'),
  NULL
FROM clients c WHERE c.name = 'Acme Co';

INSERT INTO projects (title, client_id, status, writer_id, editor_id)
SELECT '10 Mistakes New YouTubers Make', c.id, 'editing',
  (SELECT id FROM team_members WHERE first_name = 'Sofia' AND last_name = 'Test'),
  (SELECT id FROM team_members WHERE first_name = 'Leo' AND last_name = 'Test')
FROM clients c WHERE c.name = 'Acme Co';

INSERT INTO projects (title, client_id, status, writer_id, editor_id)
SELECT 'YouTube Shorts Strategy Deep Dive', c.id, 'idea', NULL, NULL
FROM clients c WHERE c.name = 'Acme Co';

INSERT INTO projects (title, client_id, status, writer_id, editor_id)
SELECT 'Client Success Story: BrightPath', c.id, 'review_script',
  (SELECT id FROM team_members WHERE first_name = 'Marcus' AND last_name = 'Test'),
  NULL
FROM clients c WHERE c.name = 'BrightPath Media';

INSERT INTO projects (title, client_id, status, writer_id, editor_id)
SELECT 'Content Calendar Planning Guide', c.id, 'ready_to_post',
  (SELECT id FROM team_members WHERE first_name = 'Sofia' AND last_name = 'Test'),
  (SELECT id FROM team_members WHERE first_name = 'Leo' AND last_name = 'Test')
FROM clients c WHERE c.name = 'BrightPath Media';
