-- 022_client_data_update.sql — Client data: new fields + Tucker Cummings
-- Reference: data-verification/clients_migration_data.txt
-- NOTE: No BEGIN/COMMIT — supabase db push wraps each file in its own transaction


-- ═══════════ 1. Insert Tucker Cummings ═══════════

INSERT INTO clients (name, status, pod_id)
  SELECT 'Tucker Cummings', 'active', p.id
  FROM pods p WHERE p.name = 'Pod 4'
  AND NOT EXISTS (SELECT 1 FROM clients WHERE name = 'Tucker Cummings');

INSERT INTO client_assignments (client_id, team_member_id, assignment_role)
  SELECT c.id, t.id, 'strategist'
  FROM clients c, team_members t
  WHERE c.name = 'Tucker Cummings' AND t.email = 'austin.marks@knownlocal.com'
  AND NOT EXISTS (
    SELECT 1 FROM client_assignments
    WHERE client_id = c.id AND assignment_role = 'strategist'
  );

-- ═══════════ 2. Status updates ═══════════

UPDATE clients SET status = 'active' WHERE name = 'Ryan Meeks' AND status = 'onboarding';
UPDATE clients SET status = 'active' WHERE name = 'Ryan Meeks - WHIP' AND status = 'onboarding';


-- ═══════════ 3. Update brand_voice_guide_url, area_guide_url, health, approval_emails ═══════════

UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1UMY51V0OP8Br42yfdg1zkI_eAotYdGZpH-epPno_Rso/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/14r-znPQAbdLjrHTdSH_g1ZZU4lcs0sg5yNVBvrLnHsk/edit?usp=drive_link' WHERE name = 'Austin Klar';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1aSyzMQ1c6m3lqVMWgBxBhwMTSaCkM5z4wo8GtQs8urc/edit?tab=t.0#heading=h.6hadevve82gr', area_guide_url = 'https://docs.google.com/document/d/17Ri8_cWAm7Ulbq5GBHY3VEgVJAlOyValeDgUBbOep-E/edit?tab=t.0', approval_emails = 'raziel@burlingameproperties.com , melissa@dubasikdigitalmarketing.com' WHERE name = 'Raziel Ungar';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://drive.google.com/file/d/1vsWKw8IUQMnO94F_FbnnyQ8QZD043krA/view?usp=drive_link', area_guide_url = 'https://docs.google.com/document/d/1kS8FjsJtcHfXDJP_BSIvWWUCLozOfee0g4fyeukk8TY/edit?tab=t.0#heading=h.5pat4cnptlcn' WHERE name = 'Scott Moe';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/12rFbOmiTLH9iDuZVY4EBcbdUItQJCnBsM5Lp6Gap8gE/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1lvIha4kD0Iy65or-uzK3iDTF4Sr1o1u-rR79JmERwDo/edit?usp=share_link', approval_emails = 'david@bruingtonhargreaves.com' WHERE name = 'David Hargreaves';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1V1PwSc9NKlI_9SneXAdyxXRFXoE6vBonhWXAJ_9G99M/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1gDpELefICzFrlV07TCXj2ej155ISMSqGYIPVLdhVzXM/edit?usp=drive_web&ouid=109194301180964155040', approval_emails = 'caroline@oylerhines.com' WHERE name = 'Oyler Hines';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1oVCUIj6vec-2fVB4g9aHPTJF7mmKdI93h198H1iTfPQ/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/16jpIa4vI7MHrJzaHbpyPomgyHnc-q4bvvfeOVLLm8WM/edit?tab=t.0#heading=h.98lxpb8wup3z', approval_emails = 'maynard@mwagnerteam.com' WHERE name = 'Maynard Wagner';
UPDATE clients SET health = 'on_track', approval_emails = 'cc@compass.com' WHERE name = 'Charles Cherney';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1b51qnZt-1WdVolIRuJcKeqtp5thSc6-GiW2-qHQgtMI/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1Hqti8-KXrJlkg9b4qcLHnV6dQkZVnReytb7nwf4yTDk/edit?usp=share_link' WHERE name = 'Joe Biscaha';
UPDATE clients SET health = 'off_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Z1gRCgIQ-zXNbbOETxo6U0_BQVLWHpyUkVZKSJhUcZo/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1TsXWdBf08riViUsTSt72vTvIip95bd8yLCXMNiSC01M/edit?tab=t.0#heading=h.1kxliojta77y', approval_emails = 'info@movingtokc.net' WHERE name = 'Kyle Talbot';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/12VxzrGKvdtxax4gErroMzQ5LUHZtWbE3iRT84I6wXOQ/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/130v0C5QiHmQ-HxIfAsGDW_fvzhPchr-5jh_3O_9kczc/edit?usp=drive_link' WHERE name = 'Brandon Blankenship';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/15O579StFXJVpJWnvxoHKy7G-7qVAJMviuqAw3nvGYEg/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1ZLoYCm-PXx6E3VjG2P0QoCClNJQjx5br9VvhQqGqVZE/edit?tab=t.0#heading=h.ms8xzk3jzwqj' WHERE name = 'Stephanie Cole Patterson';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1sXyzjgF-0c7NWrFWpdMCg_VZyTHD1W0CZUjnPe0nkV0/edit?tab=t.0#heading=h.zc57t1wd6ruc', area_guide_url = 'https://docs.google.com/document/d/1udk7QGHkH6lU2JskaT-Ms4_Js5p3RR31iAXUa1e_5qk/edit?tab=t.0#heading=h.enpsbvv4stal', approval_emails = 'marketing@theownteam.com, wilson@theownteam.com' WHERE name = 'Wilson Leung';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1QpFQUB8scVa_a6V_DXTLGVLepJbysEJkLbJS2CJggl0/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1ibxBohqwsFQmJHNij81254jQ9p3o63j3/edit' WHERE name = 'Matt Lunden';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1rUJnUn4-9SpitpliRZrEI965AIIhBy8VGNcsA-3qKQ4/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1I8Jd_jmGstJCN_W8je3Jv5obUbetMQtBQmDho1rQah0/edit?usp=drive_link' WHERE name = 'Brette Davis';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1tTBACNMdht7RDhsVbqH9jeeKX24K45xPI67Ew_Pr-Ns/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1_M_AoiQM1evpdDo7FgbqxW--7ktScBlu7pKqrAl1dBM/edit?usp=drive_link' WHERE name = 'Chris Colgan';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1xZBd2P9HbarYnxaZh23nFEn3mYqNHG4VVTI3qIbM0oM/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1bNtl1Y4a-OtRLTVMRJcnFP89Vn_sn9MX3BPrKmmKhIU/edit?usp=share_link' WHERE name = 'Will Van Wickler';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1j9-EaGYAcSBxex4WV93ecvROKGwIctJPRbs5EUMtkCA/edit?tab=t.0#heading=h.3gcowkz4q0dh', area_guide_url = 'https://docs.google.com/document/d/13b5nwXLzmUAccsks-GMq3CwBjllXfNv68KYuKpGOl6A/edit?tab=t.0' WHERE name = 'Ryan Butler';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1CHjRL52V4Z8kyO2QRCjT7QiDl-tedBq2hlyPe5hdLrk/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1c1v18w74acrg58udFuj-bpxvwNpLYgGpCo-5ku-ExGU/edit?tab=t.0#heading=h.e8sg4hjiruyq' WHERE name = 'Tiffany Pantozzi';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1JmHJnrSBhdNUjw5iCtMwlyftqKW6YK63fv5PjFCSHTI/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1gFu-N-ycQq8DjEz8JDfFwUNxTj4ZXKV6DcPY_KijQVg/edit?usp=share_link' WHERE name = 'John Sintich';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1qhLNu2lwdjrvPfksTg2iRRwoDpfmpHFqC7WAev6ux98/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1Nq6usJbpOuywSIDKxyblxsrgKDZzJTZvNEnbV7wDBwk/edit?usp=drive_link' WHERE name = 'Bern McGovern';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1IfkysTSRN2mv43tw8o7lE9iCbsNSSuWHiGD0fgxHj5U/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/11rXNf2Yd1pSxXVbN9HxulIIsAZDF7CzHi9dbD05PV9Y/edit?tab=t.0#heading=h.n8fbu8mk9vhc', approval_emails = 'michael@lifeinsanantoniotexas.com' WHERE name = 'Michael McCall';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1Yobm_wlIPd9FTkQMoDe4m46Mkk243JxUgeAApFsojos/edit?tab=t.0#heading=h.osiynv1wmndx', area_guide_url = 'https://docs.google.com/document/d/1B7n4IznAqgeSqRIjBuscAKunLrmB63NNLXPnJPG77HE/edit?usp=share_link' WHERE name = 'Isayas Theodros';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1BbDIDxFyxZWciBiup4oH5IUVKb0Lh9TB7SZ3XRSmRgk/edit?tab=t.0', area_guide_url = 'https://drive.google.com/drive/u/1/folders/1qNoOSUxVF5ryVR04eZVrFzBQ_cEId_BD', approval_emails = 'levi.lascsak@gmail.com' WHERE name = 'LID Levi Lascsak';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/19J6mxSvpTtfxaxaJq-5HYZZD-qocG8rS-dwVMEk-9ys/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/19Ob7CFRh5W0d-PIERWvyAAvOhKM_KBlN31pSXkuvKP0/edit?tab=t.0#heading=h.eigz9m1y4g8z', approval_emails = 'matt@mattoneillteam.com' WHERE name = 'Matt Oneill';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1tTBACNMdht7RDhsVbqH9jeeKX24K45xPI67Ew_Pr-Ns/edit?tab=t.0#heading=h.6oxdwugyrzq3', area_guide_url = 'https://docs.google.com/document/d/1_M_AoiQM1evpdDo7FgbqxW--7ktScBlu7pKqrAl1dBM/edit?tab=t.0#heading=h.cn8flivb3nqk' WHERE name = 'Real NoVA Network (Chris Colgan)';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/13EovGwMZrqm7Gzz4XvttzbH8n8x1IE9XuOOTGauk7s0/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1EKWOaFfx-gG4CzlRTtWoIeL2JshHWzjm30USTELWIG0/edit?tab=t.0#heading=h.eyedwqqxfnce' WHERE name = 'Sean McConnell';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1OwMC7H8XipATVFrzSLNRLsCDpgn9kbDMY2jZoIcRMyw/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1WUOsv-MHOlBGwTuFT2_JIUYAKF43w86j4_2-CfNQjYI/edit?tab=t.0#heading=h.x4gb4lyrgrch' WHERE name = 'Kristin Prough';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1qrKc79kBCCy663sy6-xlNSZ1UHBdClI9rTW2opoz0kE/edit?tab=t.0#heading=h.bak0aqwldmdp', area_guide_url = 'https://docs.google.com/document/d/1WFZtptGanSu0js3cpdp-aAVe7AYYjG4k/edit', approval_emails = 'alley.buscemi@compass.com' WHERE name = 'Alley Buscemi';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1eFf9XOTXr5w6_1X96QANvtvafOdNc5UOoDj4pEnDJbA/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1qI3JpI9156vjf0slXPEJVCsixH6w-4OgjDeCTm_AoUA/edit?tab=t.0#heading=h.ogybwppleq70', approval_emails = 'kyle@kylesimmonsteam.com' WHERE name = 'Kyle Simmons';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1xsHw4bzRf4Mqkh-OQGCNlkpjFWX4z7t6w-f01gC4ZuI/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1yTkww5Ma6bf-7leZtLffcRmEZl8O024qx1wzh_a0dnc/edit?tab=t.0#heading=h.6ow1htqzgb8b', approval_emails = 'sarah.newman@elevateteamcharleston.com' WHERE name = 'Sarah Newman';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1ohmYoPPYj8_z2QqXOt2P71lK3IiYlDfY4zNVmPdP6s8/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/19Lujn7FAB6fC7JD4X7SWDiRw6OvqVR3TbjDKLOhF3Cg/edit?usp=share_link' WHERE name = 'Erik Throm';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1nEuvWhUG2yiHrYnWfcmxWQq9Nxmn7hOFnVeIvxJqSeU/edit?tab=t.0#heading=h.6t1g1weyo71d', area_guide_url = 'https://docs.google.com/document/d/12LLv7nqDC-j2VdwExNGEsG8lAPyeQVgN9h-NxgbUOx0/edit?tab=t.0' WHERE name = 'Schmitz & Smith Group';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/16T0AjW04Zj6ys9fCDS3xbqcD86mUtOUbtQIUCz2n4oY/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1fU2DUnKRyaidmgyitDRezohnIipI2EoYNxYahpJyrgQ/edit?usp=drive_link' WHERE name = 'Connie Van';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1o5O8hb29kNlY5c77HrE60jJXBRYsil1yeuPYM8U36NE/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/16W9eYFgBvjJtJEpNeRaZYTGCejIuksgb9vDsm4VYM2g/edit?usp=share_link', approval_emails = 'gary@garybradler.com' WHERE name = 'Gary Bradler';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1bngbo8xrsiNzAvzGR4w_kNmMnver0aSCvJbFhCCRXJw/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1WF79D8lA45Eu-4DfWfM9jnIDu2o93tTskaOu7wjpb1w/edit?usp=share_link' WHERE name = 'John Garuti';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/14q6Enxb9OR1CvP22-BlINYcUyWoRxU6PukuX2f4L87U/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1Kv-pKsX6yrOELZ9jMt-akMEA0TE_qkE9kiaQrR0PaXo/edit?tab=t.0#heading=h.6u6usyrf6jjf', approval_emails = 'missy@yostgroupproperties.com' WHERE name = 'Missy Yost';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1xql3LbS8YspFKfe4F9T12rq3kbu-0DVLEixILhNSfCA/edit?usp=drive_link', area_guide_url = 'https://docs.google.com/document/d/1bomOUz10uPSLUkteWaIpBpdihmo9nHGG7SxBJUyBuSU/edit?usp=drive_link' WHERE name = 'Arjun Dhingra';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1xql3LbS8YspFKfe4F9T12rq3kbu-0DVLEixILhNSfCA/edit?tab=t.0#heading=h.4keqx8p3xzok', area_guide_url = 'https://docs.google.com/document/d/1bomOUz10uPSLUkteWaIpBpdihmo9nHGG7SxBJUyBuSU/edit?usp=share_link' WHERE name = 'LFG Energy (Arjun Podcast)';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1AOgtH-u_ex9mgjdrAIqX7qNpZxFzqBEIz7lREm1Zrw8/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1g3Gpjulzx7vDXg-T5cJOq7-hKfAu1JxZUf5PjquMe1w/edit?usp=drive_link', approval_emails = 'charity@thelivewellgroup.com' WHERE name = 'Charity & Joe Slawter';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1DkKp36nsNgM5fguQHSafw9NYT8PorjwvC8DSu75qpO8/edit?tab=t.0#heading=h.k68kphev5n3d', area_guide_url = 'https://docs.google.com/document/d/1sjHTeQ17pOi04ynmZptIhPjjttDzggSaLVg_X7nX37o/edit?tab=t.0#heading=h.k369rsq8ckne', approval_emails = 'mj@bleecher.me' WHERE name = 'Micah Bleecher';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1_aKp4uk2euX_L0i3gp8fCXqhbWgDk5cy5SvdXJqbzxM/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1aLX9gevDKTzfsXFQeym9C30KiuqZy3ZrmIkny3hEpBE/edit?tab=t.0#heading=h.cz3rwckr22zy', approval_emails = 'Lindseytronolone@gmail.com' WHERE name = 'Lindsey Tronolone';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Syzr1X-fAh6V0c8oCYIlgtIFx22gZDiq4_lDfTqIXnc/edit?tab=t.0#heading=h.cn5lowincgmb', area_guide_url = 'https://docs.google.com/document/d/1i_BGHaLogyHwP8Bh34LSE4TcJo1StYCYmPT5gQXWAts/edit?usp=drive_link', approval_emails = 'sbradthornton@gmail.com' WHERE name = 'Brad Thornton';
UPDATE clients SET health = 'at_risk', brand_voice_guide_url = 'https://docs.google.com/document/d/1NmwcaFUrCnD3xXmCtqmP4UQ2vpGrdAoxgqmLGOEw_MU/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/13IX5loTwVS7NZY1CCFbWcQhDDIXwpHM14ZDCa6pAZ00/edit?usp=drive_link', approval_emails = 'chris@whitewhalere.com' WHERE name = 'Chris Schwarz';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/12sGgyZkDdkZ-HIK4i7OTTAKZsPJwqZyiKk2UDSaHy9o/edit?tab=t.0#heading=h.l6xpt6xcqavn', area_guide_url = 'https://docs.google.com/document/d/1BjlKwIsusPv3lkJcPazRW9cC8-zZBM8Oxkjo9-RQfrw/edit?tab=t.0#heading=h.dts803p991cf', approval_emails = 'sam@lubbocktxliving.com' WHERE name = 'Sam Riddle';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Pd_ybgCJcoSJ9GCB7maXGGrOS-SNMZnZti5IHKBfJyA/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1T_dUYMCpf9iEXvBUN4pqf9mmrY0jENU0feolLVJB4mQ/edit?tab=t.0#heading=h.fnmzjdj1y3tq', approval_emails = 'landinbsmith@gmail.com' WHERE name = 'Landin Smith';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1S4_9SO6wTXCEJDHkb3uYlD91-RwYOhdMaCweRPLemxQ/edit?tab=t.0#heading=h.8td89gwa1545', area_guide_url = 'https://docs.google.com/document/d/1M_ABDd6369hexXeifj4w6wVwmc2InKjeVXk7o99dZww/edit?usp=drive_link', approval_emails = 'adam@thedowgroup.com' WHERE name = 'Adam Dow';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Rxej7wsIrilxiTz3pdv-NaPigcdsm2ysRAFNY3PaP7E/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1cjeHrvVGxbj2Zp65jF-EZdRGe-IiCH2KJO0TDXM43dk/edit?usp=drive_link', approval_emails = 'blake.ginther@theginthergroup.com, blake@theginthergroup.com, Richard_carr@me.com, erin@theginthergroup.com' WHERE name = 'Blake Ginther';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1zjF8oiSrvzjm_haAtBlt-XnZeST1Ov0oaBxbOKd7ahM/edit?tab=t.95i57fvaa33c#heading=h.9na57fl2qjit', area_guide_url = 'https://docs.google.com/document/d/1017BoBvW1lzh2kMkLapRFj23v9zIGUGxMeSSsN5Ajwo/edit?usp=share_link', approval_emails = 'brooke@hhgus.com Maria@hhgus.com' WHERE name = 'Jason & Brooke';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1v1oy8kwdepyqRjXHgLqkWLqX4nUm1UsfhWQj8bm_FKQ/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1fgIkTAXRu2Dd41Bf8rv0EFYSCsRRck6e/edit', approval_emails = 'sally.daley@elliman.com' WHERE name = 'Sally Daley';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1gF30LhAEQ651L00Qtj1ljMLbcrvvhhdNEl2ohpa-bMg/edit?usp=drive_link', area_guide_url = 'https://docs.google.com/document/d/192QniGQcxvUtix8Q6mftB6dvtXriUF_twNlgorPBX2Y/edit?tab=t.0', approval_emails = 'nic@martihampton.com' WHERE name = 'Marti Hampton';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1PLRupJkCcXGjOHpPZ0w3LfKq1ywM_qvspnPkCrTF07c/edit?tab=t.0#heading=h.hpai1blr34lh', area_guide_url = 'https://docs.google.com/document/d/1auTlxTxZxkuUGC1HVXGdX24xaQzfMaRpkND7-Mp1f8Q/edit?tab=t.0#heading=h.gzwqf8conjct', approval_emails = 'justin@justinlandisgroup.com' WHERE name = 'Justin Landis';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1tlxGiKhRXmQGp6xMbsSnSWt9rtW0h88JSajU-86VQzc/edit?tab=t.0#heading=h.p3zndhemz9j7', area_guide_url = 'https://docs.google.com/document/d/1tZxnMmy4S7upHshsJduhcCYrFcystsXeV3gCQ2YIlp4/edit?tab=t.0#heading=h.z8c785u5efdt', approval_emails = 'mark@carolinaskyre.com' WHERE name = 'Mark Weinberg';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Nus39bYq4t3GpaE5v5Dj7ewFVuXi0PJMYjKCsrGYp94/edit?tab=t.9p8jg9gtty80', area_guide_url = 'https://drive.google.com/drive/u/1/folders/1sSBO7nzSSYudJ_YTws19R_xWf9SCinaH' WHERE name = 'WHID Levi Lascsak';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1Nus39bYq4t3GpaE5v5Dj7ewFVuXi0PJMYjKCsrGYp94/edit?tab=t.0#heading=h.ty4tcvfnzl9c', area_guide_url = 'https://docs.google.com/document/d/1-hQSnHkGtmOeQ0VrCYyZFbjwok-bwDSXGT5J2kEReO8/edit?tab=t.0#heading=h.7wooykovf2or' WHERE name = 'PP Levi Lascsak';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1wVSerXF-lUUJITUtmvF1IDMNQXr6limbfsBidJEXTV4/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1v-uUJTGWl3cFrwHbJ7wFb_Z9UXEtSlzxs3XQtdZUI5I/edit?tab=t.0' WHERE name = 'Tina Gamble';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1CS5hzY-3BO5m5F6AZSa2WTBSITLR989C/edit?usp=sharing&ouid=116466702480756811083&rtpof=true&sd=true', area_guide_url = 'https://docs.google.com/document/d/1o-Ej2_L823xGyRBjZLcmUm6bspgUegpb8gQmaWX_KOA/edit?usp=sharing' WHERE name = 'Will Sawyer';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1tsvEJ83WdO0VrJNa4-QjFA7OB4gVCs6I8mlbGPnT100/edit?tab=t.0#heading=h.v8vggyx1mbe3', area_guide_url = 'https://docs.google.com/document/d/1u_wJq4eRhz9iBHjOamzOkge4K-Aj5sUWSJ0032ZxBbQ/edit?tab=t.0', approval_emails = 'mhydehomes@gmail.com' WHERE name = 'Matthew Hyde';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1B_Zk3FUhB2lFkfu-zd_Y5DtUnicoIA98L15Zw_GEw-Y/edit?usp=share_link', area_guide_url = 'https://docs.google.com/document/d/1Nq6usJbpOuywSIDKxyblxsrgKDZzJTZvNEnbV7wDBwk/edit?usp=share_link' WHERE name = 'The San Diego Scoop';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/15h0h5fNcGIG5qaeWOp3W7ZfFvAAfSheHaUmw61ZCRKI/edit?tab=t.0#heading=h.q7dyhcxy2e7b', area_guide_url = 'https://docs.google.com/document/d/1amWtx-Ok_lWDdT3rb5QLIcK-9nSXSjxu6fG5ty-pAXA/edit?usp=drive_link' WHERE name = 'Hannah Dubyne';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/14xlShAIAfONkOca2C4bZTVDaCYywagdFEQRwmUZoyUI/edit?usp=drive_link', area_guide_url = 'https://docs.google.com/document/d/1jWqfoYUXs6rW0JZMzjj3g-CzujKkufnWrKbo8LRR5Y8/edit?usp=drive_link' WHERE name = 'Jadde Rowe';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/12VxzrGKvdtxax4gErroMzQ5LUHZtWbE3iRT84I6wXOQ/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/130v0C5QiHmQ-HxIfAsGDW_fvzhPchr-5jh_3O_9kczc/edit?usp=drive_link' WHERE name = 'Brandon - Development Channel';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1YzeEkEYzE3XJQ5dw5XDXu5GgFVb_U8t4O7-jt9tlldQ/edit?tab=t.0#heading=h.lc0we9h1zx7u', area_guide_url = 'https://docs.google.com/document/d/1xG2WCrjtUMb3Y-gXmtyKqaceuwlWiCUzd04su45kaSk/edit?tab=t.0#heading=h.s7lp40yjemhg' WHERE name = 'Valerie Gonzalez';
UPDATE clients SET health = 'on_track', brand_voice_guide_url = 'https://docs.google.com/document/d/1V5fBIatvX8_DvmGW8-NoO7x8hc1TIWsfbVJAeSSOYV4/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1wTxfX-vogZGTjiQ-juk2xyzombErbiqC4JG5wsSYCUc/edit?tab=t.0#heading=h.ddiidaaxxcbn', approval_emails = 'grantirby@kw.com' WHERE name = 'Grant Irby';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1zOqIqeYBh-E1feh9lTdoyII3i4Fjpby85S1JGa4vXCA/edit?tab=t.0#heading=h.k7qu7xrp8lvj', area_guide_url = 'https://docs.google.com/document/d/1j5AsuFObpz-lKNSuCy-3knh2zFKoQMB9WA2A0GT_8sk/edit?tab=t.0' WHERE name = 'Devin Sheehan';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1cZ4JVzH6D8A2fxiszd_OlkC3e5PhnJrJniHzjiILq0M/edit?usp=sharing', area_guide_url = 'https://docs.google.com/document/d/1gFbzFZqE_bi752WE9aZw3KcZzm64_3jp2E9AXe6VajU/edit?usp=sharing' WHERE name = 'Ryan Meeks';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/10wfUkTl852I2d36nCNuDZ-c8wENT8G55eeRHoGnTJ2c/edit?tab=t.0#heading=h.3ghlz6xsmw1s', area_guide_url = 'https://docs.google.com/document/d/1cHf01gUCDzqpEFBytszSub_PJxY7ACJyDpdP6U3lI8I/edit?tab=t.0' WHERE name = 'Amy Shrader';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1Qg8JFyIHCf9JzG43VlfzIqTOaogOJ_qSZL0C0dZYnvc/edit?tab=t.0', area_guide_url = 'https://docs.google.com/document/d/1gFbzFZqE_bi752WE9aZw3KcZzm64_3jp2E9AXe6VajU/edit?usp=sharing' WHERE name = 'Ryan Meeks - WHIP';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1BkmKSCM4RccD9oiagDvyZr8lgZzPbOOZAlE0Ot3RFBg/edit?tab=t.0#heading=h.w5e8y0keaehj', approval_emails = 'william@williamburton.co' WHERE name = 'William Burton';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1Bc_DhGqVAJGykcq8A7KIW3fKeeKnN8v5Bm_tQcdL7T8/edit?usp=sharing', area_guide_url = 'https://docs.google.com/document/d/1_Ra7Bvt4fsq73vJvlKa5e4Qrqhu_jdtbrsBcgy64vW4/edit?usp=sharing' WHERE name = 'German Hernandez';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1BsKFOIs1cGnUX9HNmxexehnTA4qtQV1KkeOJsdIK7mY/edit?tab=t.0#heading=h.azug0t30sgli', area_guide_url = 'https://docs.google.com/document/d/1kp6H-BOTlAQbfiQ3xRqpxygrriq1YLSGS-2YgxYZCSQ/edit?tab=t.0#heading=h.fwgvlrhqvl5v', approval_emails = 'stephen@stephencooley.com tanner@stephencooley.com' WHERE name = 'Stephen Cooley';
UPDATE clients SET brand_voice_guide_url = 'https://docs.google.com/document/d/1jCZrquqno_8Vt-KSUwxqWea6ORwt1TVTSlbyvVLsYpc/edit?usp=sharing', area_guide_url = 'https://docs.google.com/document/d/1cOw4VN2tk5pak-GNYprnMJz5aJstiajwSfy1s4ertSM/edit?tab=t.0#heading=h.5xiskiq45o3w' WHERE name = 'Erin & Niki';

-- Total updates: 71 clients
